# These are supported funding model platforms

github: [botolmehedi, babaslab, teamvvirus]
patreon: botolbaba
open_collective: botolbaba
ko_fi: botolbaba
tidelift: npm/botolbabatool
community_bridge: botol-baba-tool
liberapay: botolbaba
issuehunt: botolbaba
otechie: botolbaba
